### ISSUE TITLE
help with connection issue

### ISSUE THREAD

**Issue by Nep-Soundfont** [iCrazyBlaze/TwitchVsMinecraft#3]
i have everything set up but i think i messed up somehow, it doesn't connect
it says it's connecting but it loops onto that and by typing the /ttv command by itself it says bot not connected, any idea why?

**Comment by Nep-Soundfont** [comment]
heres what it looks like:
![hrlp](https://user-images.githubusercontent.com/50643487/62235197-ac0dfc80-b389-11e9-8c5a-e65f030fd824.PNG)

**Comment by btarg** [comment]
Which version of the mod are you using? Also, make sure your OAuth token is valid. I'm also pretty sure channel names are case sensitive. Make sure your channel name matches exactly.

**Comment by btarg** [comment]
A new build has  been released that fixes issues with connecting to Twitch.
